packages:
  - playground
shamefullyHoist: true
strictPeerDependencies: false
ignoreWorkspaceRootCheck: true
allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  sharp: true
  unrs-resolver: true
