import fs from 'node:fs/promises'
import collections from '@iconify/collections/collections.json' with { type: 'json' }

const names = Object.keys(collections).sort()

await fs.writeFile(
  './src/collection-names.ts',
  [
    '// GENERATED BY scripts/collections.ts',
    `export const collectionNames = ${JSON.stringify(names, null, 2)}`,
  ].join('\n'),
  'utf-8',
)
